name: Run Bot

on:
  push:
    branches:
      - main  # শুধুমাত্র main ব্রাঞ্চে push হলে রান হবে

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # কোড রেপোজিটরি চেকআউট করবে

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # আপনার প্রয়োজন অনুসারে Node.js সংস্করণ ব্যবহার করুন (e.g., 14, 16, বা 18)

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm install fca-priyansh

      - name: Run bot
        run: |
          echo "Running bot..."
          node main.js || (echo "Bot run failed!" && exit 1)  # bot চালাবে, ত্রুটি হলে exit করবে
