name: Run Bot

on:
  push:
    branches:
      - main  # main branch-এ push হলে এই workflow রান হবে।

jobs:
  run-bot:
    runs-on: ubuntu-latest  # এই environment-এ রান হবে।

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # repository চেকআউট করবে।

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Node.js সংস্করণ (আপনার প্রয়োজন অনুযায়ী 16 বা 18 সেট করতে পারেন)।

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm ci  # দ্রুত সব dependencies ইন্সটল করবে।
          npm install fca-priyansh
          npm install moment-timezone  # `fca-priyansh` এবং অন্যান্য প্রয়োজনীয় প্যাকেজ ইন্সটল করবে।

      - name: Fix vulnerabilities
        run: |
          echo "Fixing vulnerabilities..."
          npm audit fix || true  # দুর্বলতা ঠিক করার চেষ্টা করবে, তবে ব্যর্থ হলেও চলবে।

      - name: Check Node.js version
        run: node -v  # Node.js সংস্করণ চেক করবে।

      - name: Run bot
        run: |
          echo "Running bot..."
          node main.js || (echo "Bot run failed!" && tail -n 20 main.js && exit 1)  # bot চালাবে, ত্রুটি হলে exit করবে এবং শেষ ২০টি লাইন দেখাবে।
