name: Run Bot

on:
  push:
    branches:
      - main  # main ব্রাঞ্চে push হলে এই workflow রান হবে

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # রেপোজিটরি চেকআউট করবে

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Node.js সংস্করণ নির্বাচন করুন (14, 16, বা 18 যেটা প্রয়োজন)

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm install  # সমস্ত প্যাকেজ ইনস্টল করবে
          npm install fca-priyansh  # fca-priyansh ইনস্টল করবে

      - name: Run bot
        run: |
          echo "Running bot..."
          node main.js || (echo "Bot run failed!" && exit 1)  # bot চালাবে, ত্রুটি হলে exit করবে
